### ISSUE TITLE
Failed to fetch json data

### ISSUE THREAD

**Issue by oPP4i** [HyperiumClient/Hyperium#145]
when it is installing, it shows these words suddenly.
"failed to fetch json data"
My java is the latest version.
And there is a 1.8.9 minecraft file as well.
What should I do?

**Comment by VRCube** [comment]
Hey thank you for reaching out to us, could you please run the JAR from cmd/terminal and send us your stacktrace?

**Comment by boomboompower** [comment]
Should have been fixed in the last few releases
