### ISSUE TITLE
[Dev B4] Youtubers in friends tab has the "YOUTUBE" part black

### ISSUE THREAD

**Issue by MODKILLER1001** [HyperiumClient/Hyperium#153]
How to replicate:

1. Launch Hyperium Dev B4 
2. Change menu style to Hyperium
3. Click the H
4. Click friends.
5. Youtubers have dark prefix.

**Comment by MODKILLER1001** [comment]
EDIT: Is database error on sk1er.club
Check the bottom of http://sk1er.club/data/snipper
It says Â§c[Â§0YOUTUBERÂ§c] Snipper"},"cache":1524412487045,"cached":false}
The §0YOUTUBER is an error, it should be §fYOUTUBER

Send help @Sk1er

**Comment by 9Y0** [comment]
probably because it has to be black on the site to see it well https://sk1er.club/stats/snipper

**Comment by MODKILLER1001** [comment]
Nope change the CSS around the site

**Comment by Sk1er** [comment]
No the Black is 100% intentional. It is far easier to see and looks better. I'm not changing my entire site for that lol
