### ISSUE TITLE
plz i need help i still have that issue i got when u release the hyperium till now  

### ISSUE THREAD

**Issue by RamDz** [HyperiumClient/Hyperium#176]
Name: jxbrowser-natives-6.19.1-natives-windows.jar
URL: https://libraries.minecraft.net/cc/hyperium/libs/jxbrowser-natives/6.19.1/jxbrowser-natives-6.19.1-natives-windows.jar
Error details: HTTP 404: Not Found
Filename on disk: 3f6d-0b92-e30e-7601
Path: C:\Users\secret\AppData\Local\Temp\3f6d-0b92-e30e-7601
Exists: file
plz plz i need help i still have that issue i got when u release the hyperium till now

**Comment by ChachyGit** [comment]
this bug is known ask a dev in the discord for help

**Comment by RamDz** [comment]
the problem no one is answering
