### ISSUE TITLE
[B7] Game screen red tint

### ISSUE THREAD

**Issue by RDIL** [HyperiumClient/Hyperium#187]
Most of the time can be fixed by reinstall of client.

Sometimes also turns red only after hitting player or getting hit

**Comment by RDIL** [comment]
Sometimes also turns red only after hitting player or getting hit

**Comment by RDIL** [comment]
![](https://cdn.discordapp.com/attachments/429311217862180867/440991079865647104/unknown.png)
What it looks like for NiteViper#5548

**Comment by boomboompower** [comment]
Cleaned up issue, any other issues of the same varient will be redirected here.

**Comment by RDIL** [comment]
Was this fixed in b8 @boomboompower ?
