### ISSUE TITLE
Fullscreen main menu overlap issue

### ISSUE THREAD

**Issue by RDIL** [HyperiumClient/Hyperium#188]
If menu style is set to Hyperium (the one with the five huge buttons lined up from left to right), the cosmetics button overlaps the Hyperium logo thing.

**Comment by iTechieGamer** [comment]
Just decrease the GUI size.

**Comment by RDIL** [comment]
Was this fixed?

**Comment by ConorTheDev** [comment]
you need to change the gui size.
