### ISSUE TITLE
Cannot see my OptiFine cape

### ISSUE THREAD

**Issue by RDIL** [HyperiumClient/Hyperium#189]
Note: I can still see my skin (This is in newest build)

**Comment by RDIL** [comment]
@boomboompower I think it may be an issue with skin changer integration because in skinchanger it says using cape = false

**Comment by boomboompower** [comment]
I disabled SkinChanger in B7

**Comment by RDIL** [comment]
oh rip
could u pls at least take a look at the issue?  thx

**Comment by ElektroKill** [comment]
Try this
Mc settings > skin customization > cape : on
Mc settings > video settings > details > show capes : on

**Comment by RDIL** [comment]
@ElektroKill already tried.

**Comment by RDIL** [comment]
@boomboompower what about the cape changer thing?

**Comment by boomboompower** [comment]
Also disabled @RDIL

**Comment by RDIL** [comment]
@KodingKing wasn’t this just fixed?

**Comment by ConorTheDev** [comment]
issue is fixed, check #changelogs in discord

**Comment by RDIL** [comment]
Last time I checked KenWay said it wasn’t fixed?

**Comment by ConorTheDev** [comment]
![image](https://user-images.githubusercontent.com/31479541/40587310-79149d96-61c5-11e8-9e68-5576488a8dbd.png)

**Comment by RDIL** [comment]
Alright thx!

**Comment by RDIL** [comment]
Fixed.
