### ISSUE TITLE
[B7] Quickplay triggering game crash

### ISSUE THREAD

**Issue by RexTheMon** [HyperiumClient/Hyperium#191]
Game crashes when changing keybind in /qp keybinds

Version b7

Edit: Actually it keeps on crashing whenever I join a server..

This is spamming mc logs. 500 lines lol
https://hastebin.com/inejawohad.swift

**Comment by Cubxity** [comment]
@bugfroggy

**Comment by bugfroggy** [comment]
This appears to be an issue with Deadma5 cosmetics.
Are you crashing, getting that spammed in your logs, or both?

**Comment by RexTheMon** [comment]
It spams logs and crashes about 10 seconds after starting up the game.

**Comment by bugfroggy** [comment]
I reported it to devs and I was told this is fixed in https://github.com/HyperiumClient/Hyperium/commit/a6e0dc8a1eb1f00a0450d5c26daa0656c99abdd0
