### ISSUE TITLE
i got red screen

### ISSUE THREAD

**Issue by RamDz** [HyperiumClient/Hyperium#193]
when i join hypixel on the lobby it's normal but when i join a game or i change lobby screen turn red

**Comment by RamDz** [comment]
https://i.imgur.com/mm6XJ3K.png and also i have problem with controls it always change

**Comment by RDIL** [comment]
Already known and being fixed.

**Comment by boomboompower** [comment]
https://github.com/HyperiumClient/Hyperium/issues/187
