### ISSUE TITLE
Client will not Install. 

### ISSUE THREAD

**Issue by TJRavenD** [HyperiumClient/Hyperium#198]
I go to download link and the download goes through. I then open up downloaded file, it installs until the last little bit of installation then stays like that. This does not change even after an hour. Any ideas. I have advised to install with only optifine and same issue occurs.

**Comment by RDIL** [comment]
@TJRavenD try installing the newest versions of JRE and JDK
(found here: http://www.oracle.com/technetwork/java/javase/downloads/index.html)
