### ISSUE TITLE
Hyperium Settings are not saved/loaded

### ISSUE THREAD

**Issue by iTechieGamer** [HyperiumClient/Hyperium#206]
Whenever I change anything in the Hyperium Settings (including Controls), they don't get loaded/saved. No Hyperium error messages found in logs

**Comment by RDIL** [comment]
Known.  Will be fixed in next update

**Comment by ChachyGit** [comment]
Will be fixed as said above, if you need me feel free to contact me on discord, my username is Chachy#1258.

Fellow Staff Team Member
