### ISSUE TITLE
Launching Hyperium 0.9.1 returns 403 error

### ISSUE THREAD

**Issue by IsaiahPatton** [HyperiumClient/Hyperium#211]
![image](https://user-images.githubusercontent.com/16439221/40271553-90a4abea-5b6c-11e8-8554-09642ef8540c.png)

![image](https://user-images.githubusercontent.com/16439221/40271525-49d64606-5b6c-11e8-826a-939a67ddab02.png)

![image](https://user-images.githubusercontent.com/16439221/40271466-bf75f434-5b6b-11e8-911d-a505d2c94685.png)

**Comment by ChachyGit** [comment]
use the new launcher, if you're on linux create a ticket in the discord so i can talk you through it

**Comment by ChachyGit** [comment]
My tag is Chachy#1258

**Comment by RDIL** [comment]
Try in new launcher and without sidebar addon.  That might be the cause.

**Comment by Amplifiable2** [comment]
@RDIL I know this is already closed, but the errors in his launcher have literally nothing to do  with sidebaraddon.

**Comment by IsaiahPatton** [comment]
so you're not supporting Hyperium on linux

**Comment by ChachyGit** [comment]
Hyperium supports Linux

**Comment by boomboompower** [comment]
https://github.com/IsaiahPatton use the new linux launcher from here

https://reddit.com/r/Minecraft/comments/5opl31/help_us_test_the_new_minecraft_launcher_now_with/
