### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by RamDz** [HyperiumClient/Hyperium#213]
When i launch minecraft it doesn't launch and the crash msg is this thing 
Failed to download file. Hyperium-0.9.2.jar
Name: Hyperium-0.9.2.jar
URL: https://libraries.minecraft.net/cc/hyperium/Hyperium/0.9.2/Hyperium-0.9.2.jar
Error details: HTTP 404: Not Found
Filename on disk: e4f4-650b-0f5e-e07f
Path: C:\Users\\AppData\Local\Temp\e4f4-650b-0f5e-e07f
Exists: file

**Comment by Sk1er** [comment]
Rerun the installer

**Comment by RamDz** [comment]
the problem is i launched the installer 20 times because of my bad internet

**Comment by RamDz** [comment]
the problem is i launched the installer 20 times because of my bad internet

**Comment by RamDz** [comment]
it doesn't work

**Comment by RDIL** [comment]
Open ticket in discord.

**Comment by RamDz** [comment]
ticket is no longer working in the discord btw

**Comment by RDIL** [comment]
@RamDz tickety is just overloaded by the number of tickets!
