### ISSUE TITLE
FortniteCompassMod is called ForniteCompassMod in the installer.

### ISSUE THREAD

**Issue by dxf** [HyperiumClient/Hyperium#221]
That is all.

**Comment by ConorTheDev** [comment]
fixing now

**Comment by dxf** [comment]
@RDIL something tells me that he knows how FORTNITE is spelled.

**Comment by RDIL** [comment]
No I was talking about how u said FortniteCompassMod but it’s
FortniteCompassAddon

Dafydd wrote:
FortniteCompassMod is called FortniteCompassMod in installer.


What you should have wrote:
FortniteCompassAddon is called FortniteCompassMod in the installer.


See the difference?

**Comment by dxf** [comment]
Wow. What a huge difference.

**Comment by RDIL** [comment]
Agree.

**Comment by Amplifiable2** [comment]
Technically, an addon is still a mod, so FortniteCompassMod isn't incorrect.
