### ISSUE TITLE
Purple screen bug

### ISSUE THREAD

**Issue by RDIL** [HyperiumClient/Hyperium#233]
Happens in newest build.  Basically same as red screen but it’s purple now lol

**Comment by ConorTheDev** [comment]
What happens before this happens?

**Comment by RDIL** [comment]
@ConorTheDev it happened to be when I adjusted my render distance but only for a second or two, and hasn’t happened since.  A lot of people have reported it in the discord also.  You might as well ask them.

**Comment by ConorTheDev** [comment]
This is going to be fixed soon, we have a stack trace and will be looking into it.

**Comment by RDIL** [comment]
Alright!   Should I close the issue now @ConorTheDev ?

**Comment by ConorTheDev** [comment]
When it's fixed.

**Comment by ConorTheDev** [comment]
As the issue is not dealt with.
