### ISSUE TITLE
[FIXED]INSTALLATION FAILED

### ISSUE THREAD

**Issue by PouriaA2** [HyperiumClient/Hyperium#236]
Hi
I Wan't to install hyperium client but when Im going to it
it says:
INSTALLATION FAILED
FAILED TO GATHER REQUIRED FILES
My specs:
8G RAM
NVIDIA GEFORCE 1050
I gaved 6G Ram to the client to install
And sorry for my bad english

**Comment by realxaii** [comment]
try 4gbs of ram?

**Comment by boomboompower** [comment]
@PouriaA2
Press 'L' and send the copied contents to a ticket on the discord

**Comment by PouriaA2** [comment]
@realxaii I gaved 4gbs of ram but doesnt work
yea i downloaded

**Comment by PouriaA2** [comment]
@boomboompower what server?

**Comment by PouriaA2** [comment]
@boomboompower Pressed "L" But it didn't copy it to the clipboard

**Comment by RDIL** [comment]
@PouriaA2 can you access Sk1er.club and Hyperium.cc in your web browser?

**Comment by PouriaA2** [comment]
Umm My problem is fixed
This was about my slow connection so the client wasn't able to download the files
