### ISSUE TITLE
Constant Crashing

### ISSUE THREAD

**Issue by SianKhanA** [HyperiumClient/Hyperium#297]
It has been a few days since I have been using the b12 version and I constantly keep crashing everytime I try to play, the screen freezes and then the client crashes, please pm me the fix on my discord. Sian#6738

**Comment by SHARDcoder** [comment]
what's your ign and what addons are you using

**Comment by SianKhanA** [comment]
Squeakerbilly/CharcoalSnowman
And I just use the Oof add-on and some other but not much
