### ISSUE TITLE
Crash when opening setings GUI from Main Menu

### ISSUE THREAD

**Issue by datitisev** [HyperiumClient/Hyperium#305]
http://hastebin.com/igovuxareg

Hyperium: 1.0 - Beta B13
Addons: ForniteCompassMod, Quickplay, SidebarAddon,

**Comment by liach** [comment]
Same https://gist.github.com/liach/37360b04368f929186af4376d6616060

**Comment by liach** [comment]
Erroneous line: https://github.com/HyperiumClient/Hyperium/blob/1a342ee22d7c1a0f5ca883d2f04d20b8ba26e28c/src/main/java/cc/hyperium/gui/main/tabs/SettingsTab.java#L242

Situation of the above crash: was playing in dream bedwars, pressed
```
`
```
and game crashed.

**Comment by liach** [comment]
Well, the instance of cosmetics should have been initialized here: 
https://github.com/HyperiumClient/Hyperium/blob/1a342ee22d7c1a0f5ca883d2f04d20b8ba26e28c/src/main/java/cc/hyperium/Hyperium.java#L129
Don't know what caused the NPE exactly. Needs more debugging.

**Comment by Sk1er** [comment]
I've fixed this fore b14.  I set the cosmetics to initialize earlier in the constructor as a bandaid. I'm looking into where an exception could be thrown that stopped the loading from happening before that point
