### ISSUE TITLE
It's like you don't even want us to contribute

### ISSUE THREAD

**Issue by okx-code** [HyperiumClient/Hyperium#312]
```
Q: Please help, I can't build Hyperium!

A: Wait for a new beta or release!
```

This is not helpful at all. Some people might actually want to make a PR to improve the code and if they come across a problem in building and see this they might just give up contributing.

**Comment by liach** [comment]
`gradle jar`?

**Comment by ConorTheDev** [comment]
The OP is saying like it's for us not to contribute, if you **wanted** contribute you would **know** how to build the workspace.

**Comment by ConorTheDev** [comment]
> Some people might actually want to make a PR to improve the code and if they come across a problem in building and see this they might just give up contributing.

1st of all, if they gave up that quickly they shouldn't code at all.
2nd, back to my first message, they would **know** how to do it so they wouldn't run into this issue.

**Comment by okx-code** [comment]
When I was trying to compile this, I had to use one specific gradle version to setup the decomp workspace and another to compile it. Then, Kotlin didn't even work (I made a separate issue to try to convert Kotlin code into Java)

**Comment by ConorTheDev** [comment]
That is the way most gradle projects are sometimes. Kotlin not working is something on your side.

**Comment by okx-code** [comment]
Are you sure most gradle projects require two different versions to do different things? I don't think so.

**Comment by ChachyGit** [comment]
im sure

**Comment by RDIL** [comment]
this needs to be closed it has basically no use / purposes

**Comment by ChachyGit** [comment]
```yes```

**Comment by boomboompower** [comment]
If you have any issues building the project ask for help in the discord
