### ISSUE TITLE
Hud does not render

### ISSUE THREAD

**Issue by VRCube** [HyperiumClient/Hyperium#33]
sometimes hud does not render and I need to restart MC

**Comment by boomboompower** [comment]
Theres a hud?

**Comment by Sk1er** [comment]
Any info how it happened / logs? Have not been able to reproduce

**Comment by Sk1er** [comment]
` 
  if (!this.minecraft.inGameHasFocus || this.minecraft.gameSettings.showDebugInfo) 
            return
  if (!Hyperium.INSTANCE.getHandlers().getHypixelDetector().isHypixel())
            return;
`
One of those things, likely hypixel so not a bug a feature.

**Comment by VRCube** [comment]
Sometimes nothing renders that is hooked to render event (ex: Notification center) but i don't know if issue still exists, if it is I'll reopen
