### ISSUE TITLE
Spotify integration broken (possible fix concept included)

### ISSUE THREAD

**Issue by dxf** [HyperiumClient/Hyperium#400]
I'm pretty sure the reason why it no longer works is cause Spotify removed its local API in favour of its web based one. 

I found this out cause Snip (app that fetches Spotify playing info) no longer works, but someone made a c# fix for it on the Snip repo https://github.com/dlrudie/Snip/pull/303

So, the solution is to find/create a java implementation of said API and use it to get info instead of local API.

**Comment by ChachyGit** [comment]
hm

**Comment by ChachyGit** [comment]
I say we should use this https://github.com/thelinmichael/spotify-web-api-java

**Comment by dxf** [comment]
I just noticed I got issue #400 👀

**Comment by boomboompower** [comment]
@dxf Nice

I'm currently looking into using the web api and playing around with it a bit. One issue right now is the requirement of Spotify Web Tokens (since they'll have to be publicly available). 

More info on the web api may be brought here soon.

**Comment by dxf** [comment]
@boomboompower what you could do is use a python script to use one of the remote controllable browser libraries (forgive me I don't remember what they're called, it let's a python script control chrome/Firefox) to automatically create a new API application, which then uses something like this: https://github.com/JMPerez/spotify-web-api-token to get the token required to connect to spotify.

Obviously it can all be done in Java but that's just how I understand it.

**Comment by dxf** [comment]
This would be done on a per user basis, so then each user has their own tokens that Hyperium can use when it does the Spotify integration

**Comment by dxf** [comment]
My concept:

App with Spotify web API running in a server on the cloud, fetching data for all online users every x seconds.

When player opens Hyperium for the first time, pop up "do you want to set up Spotify? If you want to do it later, go to Hyperium settings". Upon clicking yes, Spotify oauth flow open, asks user to allow Hyperium access to user data. On accepting, it then goes to Hyperium site with a token to paste into Hyperium that links Hyperium client with the Spotify account of that user. The same token is stored on the server to associate usernames with clients to fetch data every X seconds and send it.

The server then pings the client via it's token every x seconds with the Spotify data of the user, which is parsed and displayed.

**Comment by Camnooten** [comment]
Are you thinking of selenium for Python? @dxf

**Comment by dxf** [comment]
YES!

**Comment by RDIL** [comment]
maybe we see what discord is doing for it?

**Comment by asbyth** [comment]
not being reintegrated to hyperium, may be included as an addon whenever another mod is done
