### ISSUE TITLE
Button size wrong

### ISSUE THREAD

**Issue by ghost** [HyperiumClient/Hyperium#409]
When Hyperium is fullscreen or maximum window size, button went to out of screen.
![image](https://user-images.githubusercontent.com/26434739/43435267-2c3d25ba-94ba-11e8-98cc-edec006e1f3a.png)

**Comment by ConorTheDev** [comment]
Is this still an issue? Just wondering.

**Comment by SiroQ** [comment]
yeah it's still an issue
