### ISSUE TITLE
Spotify notification 

### ISSUE THREAD

**Issue by boomboompower** [HyperiumClient/Hyperium#45]
There are two issues with the current implementation:

The notification for a new song is inconsistent and does now always occur

The song name can go off the screen, not exactly ideal, however it's an easy fix

_Extension for issue #44_

**Comment by FalseHonesty** [comment]
Song name is now wrapped around, and the height of the notification is extended to match. Ex. http://i66.tinypic.com/xee61x.png

Notifications also queue now, so there won't be any lost notifs if one is already showing. Also, not sure about the notification not showing up, but it seems to have showed up for me every time I tested, but until that has been proven, I will leave this issue open.

**Comment by boomboompower** [comment]
Alright cool @FalseHonesty I'll play around with the changes and see if that notif issue is fixed
