### ISSUE TITLE
The use of "blacklist" is offensive!

### ISSUE THREAD

**Issue by ethug** [HyperiumClient/Hyperium#450]
We should change it to blocklist. Let's do it! For a bright future!

Please read: https://twitter.com/andrestaltz/status/1030200563802230786

Software development still has a lot of terminology with a racist or patriarchal background. Let's change that.

    Blacklist ➡ Denylist
    Whitelist ➡ Allowlist
    Killer app ➡ Beloved app
    Master/slave ➡ primary/replica

Related code:

https://github.com/HyperiumClient/Hyperium/blob/a4d7e44208abfc31433d4521f2e50053e0690801/src/main/java/cc/hyperium/mods/autofriend/AutofriendMod.java#L22

https://github.com/HyperiumClient/Hyperium/blob/a4d7e44208abfc31433d4521f2e50053e0690801/src/main/java/cc/hyperium/mods/autofriend/AutofriendMod.java#L58-L71

https://github.com/HyperiumClient/Hyperium/blob/a4d7e44208abfc31433d4521f2e50053e0690801/src/main/java/cc/hyperium/mods/autofriend/AutofriendMod.java#L73-L98

https://github.com/HyperiumClient/Hyperium/blob/a4d7e44208abfc31433d4521f2e50053e0690801/src/main/java/cc/hyperium/mods/autofriend/command/AutofriendCommand.java#L48

**Comment by RDIL** [comment]
Hello there!  If you think you can improve Hyperium’s code, please open a
pull request!

Have a nice day :)

**Comment by ethug** [comment]
> 
> Hello there! If you think you can improve Hyperium’s code, please open a pull request! Have a nice day :)

I doubt you'd accept a request to delete the project!  The original maintainers must understand the importance of putting an end to racial discrimination and the horrible terminology related to our horrific past with issues related.  Please look into your heart and consider changing your ways for a more positive future!

**Comment by RDIL** [comment]
Hey, I’m not the one who merges PRs here.  Infact, I do agree with this
movement.

**Comment by Sk1er** [comment]
Minecraft calls the list of players that can join when restricted a "whitelist" therefore they are racist.

**Comment by ethug** [comment]
So you accept their standards and continue with racial terms?  Incredible.  Movements are started and propelled by people and you give up.  Shame on you.

**Comment by asbyth** [comment]
grr the english language is racist grrr angwy >:(

**Comment by Sk1er** [comment]
https://www.quora.com/Is-the-term-blacklist-racist

**Comment by ethug** [comment]
> 
> 
> grr the english language is racist grrr angwy >:(

> 
> 
> https://www.quora.com/Is-the-term-blacklist-racist

Racism is not a joke and this is extremely saddening to understand the immaturity of you and the other developers behind this project.  Soon you will realize the importance of this movement!  Your racist ways have no place in this community.

**Comment by KodingKing1** [comment]
I’m really tempted to make a “family friendly mode” that replaces all instances of text that could be considered racist with other words just as a joke.

**Comment by Sk1er** [comment]
@ethug I'm not being racist. If you read the article you would have learned that the term "blacklist" has nothing to do with race.

**Comment by KodingKing1** [comment]
@ethug If you find the terms offensive it don’t like them, simply don’t use the client. Just don’t complain about it.

**Comment by ethug** [comment]
> 
> 
> @ethug I'm not being racist. If you read the article you would have learned that the term "blacklist" has nothing to do with race.

You're a racist and in the stage of denial.  A Quora article is nothing but biased opinions and views from radicals giving their opinions on the subject and vote on an "answer".  That is not a valid response nor any place to "learn" something.
