### ISSUE TITLE
Make animated (chroma) packs work please!

### ISSUE THREAD

**Issue by V3XX** [HyperiumClient/Hyperium#532]
**Is your feature request related to a problem? If so, please describe.**   
A clear and concise description of what the problem is. Ex. Spotify integration is broken (which is already known don't report it)  

**Describe the solution you'd like**

**Describe alternatives you've considered**  

**Additional context**

Make chroma packs work please, the armor isn't animated
this may be because of resource pack organizer or something, so please add a way to disable that
thanks :)

**Comment by asbyth** [comment]
check your animations, you may have them disabled, what version are you on?

**Comment by V3XX** [comment]
i have all animations on, and on hyperium 1.8.9

**Comment by RDIL** [comment]
Works fine for me

**Comment by RDIL** [comment]
Please close this unless resetting video settings then trying doesn’t work.
