### ISSUE TITLE
odd nametag / levelhead thingy

### ISSUE THREAD

**Issue by RDIL** [HyperiumClient/Hyperium#535]
**Describe the bug**  
Two bugs:
first; levelhead too low :/
second; if you crouch you see blurred nametag if setting to show own nametag is off

**Expected behavior**  

**Screenshots**  
https://drive.google.com/open?id=1PssJepFt4J-DkNkaqHmLvI-riB9fdERF 

**Desktop (please complete the following information):**  
 - OS: Windows 10 Home Build 10.0.17134.345
 - Version Hyperium Beta Build 2167  

**Additional context**
Its so odd lol  

**Logs**  
If you need logs I can attach.

**Comment by Sk1er** [comment]
![](https://sk1er.exposed/21.46.21-05.11.18.png)
Can't seem to replicate improper Levelhead settings
