### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by RDIL** [HyperiumClient/Hyperium#536]
**Describe the bug**  
Sometimes on lobby join everything will be blurred but 

**To Reproduce**  
1. Join lobby 
2. It might happen

**Expected behavior**  
It shouldn't be blurred

**Screenshots**  
https://drive.google.com/open?id=1gMoVs_IVzUFpVCkQ423AGCCbDWNw5Vxh (up close)
https://drive.google.com/open?id=15wlwrYzuCzPEThS8cOSeFiz4mTx5C0QG (from further away)

**Desktop (please complete the following information):**  
 - OS: Windows 10 Home Build 10.0.17134.345
 - Version: Hyperium Beta Build 2167

**Additional context**
It happened once when directly joining hypixel after starting game and once after /l-ing from a skywars game

**Logs**  
If you need logs I can attach them for you.

**Comment by Sk1er** [comment]
Should be fixed
