### ISSUE TITLE
GUI slighly moves on open

### ISSUE THREAD

**Issue by RDIL** [HyperiumClient/Hyperium#537]
**Describe the bug**  
It seems that in this beta build, the GUI moves up-left a few pixels when you open any GUI

**To Reproduce**  
1. Go on beta build
2. Open GUI
2.1. Look closely!   

**Expected behavior**  
It should not be moving up-left.  

**Screenshots**  
https://drive.google.com/open?id=1TOyNPdRMbenjH2PtfR9xOLACByH52ZHO (yea im sorry its hard to see)

**Desktop (please complete the following information):**  
- OS: Windows 10 Home Build 10.0.17134.345
- Hyperium Version: Hyperium Beta Build 2167

**Additional context**
It may have to do with @KodingKing1's GUI blurring thing

**Logs**  
If you have any logs, put them here.

**Comment by Sk1er** [comment]
I think thats just a side effect of the blur algorythm. Not sure if we can do anything about it
