### ISSUE TITLE
Green screen bug

### ISSUE THREAD

**Issue by RDIL** [HyperiumClient/Hyperium#538]
**Describe the bug**  
ugh :/

**Expected behavior**  
It shouldn't happen

**Screenshots**  
https://drive.google.com/open?id=1ghSZctSZsyf762bBCRlMLCOqaiL-pMQ5 (not photoshopped/edited)

**Desktop (please complete the following information):**  
 - OS: Windows 10 Home Build 10.0.17134.345
 - Version: Hyperium Beta Build 2169 

**Logs**  
If you need logs I can provide.

**Comment by RDIL** [comment]
(its green/blue this time forgot to say that)

**Comment by CoalCoding** [comment]
Did you have fast render set to OFF? Also is this still an issue on the latest build?

**Comment by RDIL** [comment]
Fast render is on, happens on the beta that came out yesterday.

**Comment by RDIL** [comment]
@CoalCoding update: somebody found out it started after the beta of this commit: https://github.com/HyperiumClient/Hyperium/commit/d9859cdf5c14855ce879c23cb3da789cf1f1de6b

**Comment by RDIL** [comment]
I have given Coal all the info so I'm going to close this now

**Comment by RDIL** [comment]
Possibly fixed by 661a405

**Comment by RDIL** [comment]
https://cdn.discordapp.com/attachments/460132259417292800/531969825681965076/unknown.png
