### ISSUE TITLE
TOS Accept brings you to the Settings Menu

### ISSUE THREAD

**Issue by ConorTheOreo** [HyperiumClient/Hyperium#54]
it happens sometimes. here's a gif

![2018-03-02_11-26-27](https://user-images.githubusercontent.com/31479541/36896964-a0e8dffa-1e0c-11e8-84d0-9bdd70496569.gif)

**Comment by FalseHonesty** [comment]
I believe this is due to the accept button being in the same location as the button to open settings. If you click it very quickly and move away your mouse it wont happen, so im pretty sure that that's the cause.

**Comment by ConorTheOreo** [comment]
i only clicked it once tho 🤔

**Comment by ConorTheOreo** [comment]
yeah

**Comment by boomboompower** [comment]
Fixed
