### ISSUE TITLE
Water bug

### ISSUE THREAD

**Issue by RDIL** [HyperiumClient/Hyperium#541]
**Describe the bug**  
When going into water the font file opens

**To Reproduce**  
1. Start hyperium
2. Go into water
3. bam

**Expected behavior**  
It shouldn't open the font file

**Screenshots**  
1. https://cdn.discordapp.com/attachments/429311217862180867/509517671813873675/2018-11-06_18.57.02.png
2. https://cdn.discordapp.com/attachments/429311217862180867/509517686280028190/2018-11-06_18.57.06.png

**Additional context**
It happened on VanityMC space realm

**Comment by simonri** [comment]
Did you use the "Improve font"-thing setting?

**Comment by RDIL** [comment]
Not sure, I’ll look into it.

**Comment by RDIL** [comment]
Nope.

**Comment by RDIL** [comment]
No leads, closing.
