### ISSUE TITLE
Please remove certain commands

### ISSUE THREAD

**Issue by V3XX** [HyperiumClient/Hyperium#543]
**Describe the bug**  

**To Reproduce**  
1. 
2. 
3. 

**Expected behavior**  

**Screenshots**  

**Desktop (please complete the following information):**  
 - OS: [e.g. Windows 10]  
 - Version [e.g. Hyperium Beta Build 1337]  

**Additional context**

**Logs**  
If you have any logs, put them here.  

because of the clients, the /party, /msg, and other commands that are apparently part of the client do NOT work on servers that aren't hypixel
please fix this, thanks!

**Comment by asbyth** [comment]
/disablecommand <command> was added for a reason

**Comment by RDIL** [comment]
Also if you click bug report please actually fill out the format this is
making my eyes bleed

**Comment by V3XX** [comment]
sorry RDIL. but also /disablecommand doesn't seem to exist

**Comment by RDIL** [comment]
Try using latest beta.

**Comment by Mystyy** [comment]
You need to do /disablecommand <command>

**Comment by RDIL** [comment]
Please close this issue.
