### ISSUE TITLE
Victory royale mod addition

### ISSUE THREAD

**Issue by RDIL** [HyperiumClient/Hyperium#573]
**Is your feature request related to a problem? If so, please describe.**   
  
No it is not.  

**Describe the solution you'd like**
  
Sk1ers new mod to be added to Hyperium with a toggle like the rest.  

**Describe alternatives you've considered**  
  
I don’t know any other mods that do this

**Additional context**
  
https://github.com/Sk1er/VictoryRoyaleMod

**Comment by asbyth** [comment]
already planned do u not see the trello

**Comment by RDIL** [comment]
Just created this so people can see its planned

**Comment by asbyth** [comment]
https://github.com/HyperiumClient/Hyperium/pull/577
