### ISSUE TITLE
Hyperium Startup Failure

### ISSUE THREAD

**Issue by Jorseii** [HyperiumClient/Hyperium#593]
**Cause**  
Steps to reproduce the crash:  
1.   Install Hyperium 
2.  Start the launcher
3.  Start Hyperium

**Desktop (please complete the following information):**  
 - OS: [e.g. Windows 10]  Windows 10
 - Version [e.g. Hyperium Beta Build 1337]  Hyperium Beta Build 2409

**Logs**  
  
https://pastebin.com/NEeetmHb

**Comment by asbyth** [comment]
use a version below 2403

**Comment by RDIL** [comment]
Now fixed.

**Comment by Jorseii** [comment]
Thank you, closing this issue.

Best regards
#
