### ISSUE TITLE
Game freezes when joining lobbys

### ISSUE THREAD

**Issue by Kyxr** [HyperiumClient/Hyperium#599]
Every time I log onto Hypixel (I haven't tried other servers yet) and join a lobby my game freezes and stays frozen for a good minute or so then I get disconnected from the server. I have only gotten this client yesterday and I love it but I literally cant join a lobby other than mega walls without getting disconnected. This also happens when I just join a game I freeze and eventually get kicked from the entire server.
**To Reproduce**  
1.  Join Hypixel
2.  Join a game
3.  OR Join Hypixel
4. Join a different lobby than the one im in.

**Expected behavior**  
  
I should be able to load into games and other lobbys without my game freezing and then getting disconnected from hypixel.

**Screenshots**  
  
I dont have any

**Desktop (please complete the following information):**  
 - OS: [e.g. Windows 10]  Mac OS Sierra
 - Version [e.g. Hyperium Beta Build 1337]  Hyperium 1.8.9 build 2179 version 1.0.2

**Additional context**
  

**Logs**

**Comment by RDIL** [comment]
Try disabling all the optimized stuff in the improvements section of
Hyperium settings.

**Comment by asbyth** [comment]
may be fixed next within the next update, test it whenever it releases
