### ISSUE TITLE
MultiMC Support

### ISSUE THREAD

**Issue by Vresod** [HyperiumClient/Hyperium#633]
Currently, there is no (clear) way to install Hyperium onto the MultiMC Launcher. (if i'm wrong, please tell me as i would like to know). 

I've tried adding the hyperium jar (from the ".minecraft/versions/Hyperium 1.8.9" directory) to the jar and a whole bunch else, but it throws [this](https://hastebin.com/raw/aqoxakuked) error.

Any way to make Hyperium function under MultiMC?

**Comment by RDIL** [comment]
Hyperium is supposed to be compatible.  What build of Hyperium are you using?

**Comment by Vresod** [comment]
I've tried both of the downloads (Latest Version and Universal Installer) from the website.

**Comment by asbyth** [comment]
go in the discord, some user named modkiller or something like that knows how

**Comment by loper12** [comment]
If you set the installer to the multimc directory, it should see that it's multimc, and install it in multimc.

**Comment by avicados** [comment]
what version of the download do you need? I've tried with the newest version but since it doesn't ask for where you want to store the .jar I don'r know what to do either

**Comment by Vresod** [comment]
> 
> 
> If you set the installer to the multimc directory, it should see that it's multimc, and install it in multimc.

Could you elaborate on this? What do you mean by MultiMC directory, the instance or the directory with the executable in it?

**Comment by asbyth** [comment]
multimc has support, it's just not an easy method to go through, may be easier in the future however, closing
