### ISSUE TITLE
Config header goes darker everytime you go into a new settings

### ISSUE THREAD

**Issue by KevinPriv** [HyperiumClient/Hyperium#64]
http://kevin.hypixel.life/meme841.gif

**Comment by ConorTheOreo** [comment]
is it still an issue?

**Comment by boomboompower** [comment]
Yes @ConorTheOreo I can still reproduce it

**Comment by ConorTheOreo** [comment]
I'll have a look and see.

**Comment by ConorTheOreo** [comment]
Probably wont do much because apparently my code is shit.

**Comment by FalseHonesty** [comment]
I believe this is an issue with re-instantiating the button but the old one not getting removed or something of the sort. I will take a look today.
