### ISSUE TITLE
hyperium menu visual glitch thing

### ISSUE THREAD

**Issue by w08ahd8t29807** [HyperiumClient/Hyperium#643]
So I tried out the hyperiums main menu thing and uh.. 
This is what happens..
https://gyazo.com/57b0429f906465de44b27c6ff19e4ada

yeah...
I restarted hyperium and put it to default and then the hyperium thing and its still not fixed...

oh and one more thing..
_**H**_

**Comment by RDIL** [comment]
Hello,
This is known.

**Comment by w08ahd8t29807** [comment]
oh ok
