### ISSUE TITLE
Font doesn't render correctly on Linux (Ubuntu)

### ISSUE THREAD

**Issue by infrustrationMC** [HyperiumClient/Hyperium#650]
**Describe the bug**  

When I apply a resource pack, the font failed to display

**To Reproduce**  
1.  Apply a resource pack
2. Wait

**Expected behavior**  
 
Font show normally

**Screenshots**  
  
https://imgur.com/a/8X015oD

**Desktop (please complete the following information):**  
 - OS: Ubuntu 18.04.2 LTS
 - Version: Hyperium 1.0.2

**Additional context**
  

**Logs**

**Comment by infrustrationMC** [comment]
The bug only occur when "Optimized Font Render" is on

**Comment by RDIL** [comment]
well then turn it off genius

**Comment by asbyth** [comment]
sorry for the rude comment above, we're aware of this issue but dont have a fix, only thing you could do is turn it off and wait for it to be fixed (if ever)

**Comment by asbyth** [comment]
fixed in the next version, should be released soon
