### ISSUE TITLE
Visual armour bug

### ISSUE THREAD

**Issue by SHARDcoder** [HyperiumClient/Hyperium#651]
**Describe the bug**  

Armour that a player is not wearing appears when doing certain dances

**To Reproduce**  
1.  Wear any piece of armour except leggings
2.  Default dance / Twerk
(3rd person mode to see the bug)

**Expected behavior**  
  
Armour appears normal

**Screenshots**  
  
(textures coloured differently to prove its rendering the other armour pieces)
https://shardcoder-is-a.dead-me.me/i/8ehh.png
https://shardcoder-is-a.dead-me.me/i/51pq.png
https://shardcoder-is-a.dead-me.me/i/ekro.png
https://shardcoder-is-a.dead-me.me/i/api5.png

**Desktop (please complete the following information):**  
 - OS: [e.g. Windows 10]  Windows 10
 - Version [e.g. Hyperium Beta Build 1337]  : beta released on 11th Feb

**Additional context**
  
I found this bug last year :/

**Logs**  
  
N/A - visual glitch

**Comment by asbyth** [comment]
mitch originally said that he cant do anything about it and im definitely not diving into the hours of pain he endured making this so
