### ISSUE TITLE
Custom keybind crash

### ISSUE THREAD

**Issue by SHARDcoder** [HyperiumClient/Hyperium#652]
**Describe the bug**  

When clicking on the box tagged 'listening..' when editing a custom keybind in the /keystrokesmod gui, the game crashes

**To Reproduce**  
1.  /keystrokesmod
2.  Edit custom keys
3.  Change bind
4.  Click the button again

**Expected behavior**  
  
It registers as 'LMB'

**Screenshots**  
  

**Desktop (please complete the following information):**  
 - OS: [e.g. Windows 10]  windows 10
 - Version [e.g. Hyperium Beta Build 1337]  beta from 11th of feb

**Additional context**
  
N/A

**Logs**  
  
https://hastebin.com/dicabimepu

**Comment by RDIL** [comment]
hastebin link is broken

**Comment by asbyth** [comment]
fixed in the next version, should be released soon
