### ISSUE TITLE
Chestplate arm textures are broken

### ISSUE THREAD

**Issue by SHARDcoder** [HyperiumClient/Hyperium#654]
**Describe the bug**  

The rendering of chestplate arms is wrong

**To Reproduce**  
1.  wear a chestplate
2.  activate 360 degree camera to see it
3.  zoom in with optifine for better image

**Expected behavior**  
  
the armour renders normally
normal minecraft:
https://shardcoder-is-a.dead-me.me/i/0kcy.png
https://shardcoder-is-a.dead-me.me/i/buvy.png

**Screenshots**  
  
https://shardcoder-is-a.dead-me.me/i/olwl.png
https://shardcoder-is-a.dead-me.me/i/6vtx.png

**Desktop (please complete the following information):**  
 - OS: [e.g. Windows 10]  win 10
 - Version [e.g. Hyperium Beta Build 1337]  build from feb 11th

**Additional context**
  
works for all armour types

**Logs**  
  
N/A

**Comment by asbyth** [comment]
all screenshot links are dead and nothing seems to be wrong with it, going to assume fixed
