### ISSUE TITLE
when i join the client i can't see anything like "Singleplayer" "Multiplayer" and so on

### ISSUE THREAD

**Issue by MissIntensive** [HyperiumClient/Hyperium#656]
**Describe the bug**  

**To Reproduce**  
1.  
2.  
3.  

**Expected behavior**  
  

**Screenshots**  
  

**Desktop (please complete the following information):**  
 - OS: [e.g. Windows 10]  
 - Version [e.g. Hyperium Beta Build 1337]  

**Additional context**
  

**Logs**

**Comment by asbyth** [comment]
fixed in the next version, should be released soon
