### ISSUE TITLE
Bug x. Hyperium 

### ISSUE THREAD

**Issue by RandomMinecraftKid** [HyperiumClient/Hyperium#657]
I have this bug where all the letters are invisible an flicker from time to time. I don't know what to do about it.

1.  Install Hyperium v. latest
2.  log in
3.  Thats all i did lol

**Expected behavior**  
  

https://gyazo.com/bb2866fdf30af590f7a69a7cc411dc39

 - windows 10
 - Version 1.0.2 build 2179

**Comment by asbyth** [comment]
fixed in the next version, should be released soon
