### ISSUE TITLE
MultiMC update failed

### ISSUE THREAD

**Issue by JosephTheTank13** [HyperiumClient/Hyperium#658]
**Describe the bug**  
After installing hyperium to MultiMC and trying to launch it, it says `Instance update failed because: Some artifacts marked as 'local' are missing their files:`

**To Reproduce**  
1.  Install MultiMC 5
2.  Install latest Hyperium from the Normal installer, also the universal installer doe the same thing.
3.  Try to run Hyperium from the MultiMC instance

**Expected behavior**  
Hyperium should have started and ran fine.

**Screenshots**  
![Capture](https://user-images.githubusercontent.com/28242145/61173483-eb52e580-a561-11e9-9ff2-fbe3e6674d5d.PNG)

**Desktop (please complete the following information):**  
 - OS: Windows 10
 - Version Hyperium 1.0.2

**Additional context**
`Instance update failed because: Some artifacts marked as 'local' are missing their files:
D:/User/MultiMC/instances/Hyperium 1.8.9/libraries/Hyperium-LOCAL (0).jar
D:/User/MultiMC/instances/Hyperium 1.8.9/libraries/launchwrapper-Hyperium.jar
D:/User/MultiMC/instances/Hyperium 1.8.9/libraries/OptiFine-1.8.9_HD_U_I7.jar

You need to either add the files, or removed the packages that require them.
You'll have to correct this problem manually.
`
Note that I changed my Profile name to "User"

**Comment by JosephTheTank13** [comment]
I got it to work

**Comment by douglasb2310** [comment]
Could you give me your .json file? I really want to play Hyperium on MultiMC and it has no official support.

**Comment by Systemless03** [comment]
> Could you give me your .json file? I really want to play Hyperium on MultiMC and it has no official support.

We're working on supporting it in the next installer version. You could've asked this question in the discord by the way.
