### ISSUE TITLE
Hyperium Crashes when searching for resourcepacks

### ISSUE THREAD

**Issue by AGudMineman** [HyperiumClient/Hyperium#659]
**Cause**
When using the resourcepacks menu to search for resourcepacks the game crashes.

Steps to reproduce the crash:  
1. Launch Hyperium from the vanilla launcher with 2GB of ram allocated  
2. Open resourcepacks from the escape menu
3. Search for anything in the resourcepack search box.

**Desktop**  
 - OS: Windows 8.1 (Latest updates installed)
 - Version Hyperium Beta Build 2592
 - CPU: i3-7300 @ 4Ghz
 - GPU: NVIDIA GeForce GTX 1050Ti
 - RAM: 8GB DDR4 2400MHz (2.4Ghz)

**Additional context**  
I doubt this is relevant but this is a screenshot of my resourcepacks folder: http://prntscr.com/ohqk4z

At the time I was using the resourcepack "!   TheLegend28"
Download: http://www.mediafire.com/file/8q84f4bp4rstro8/%2521_TheLegend28.zip/file

**Logs**  
Web view: https://paste.ee/p/jpOGL
Download: [latest.log](https://github.com/HyperiumClient/Hyperium/files/3413777/latest.log)

**Comment by asbyth** [comment]
fixed in the next version, should be released soon
