### ISSUE TITLE
can't download Hyperium-LOCAL.jar

### ISSUE THREAD

**Issue by SkilledTheGamer** [HyperiumClient/Hyperium#684]
**Cause**  
Steps to reproduce the crash:  
1.   Downloading the installer
2.  Install it like normal
3.  Open the launcher and launch Hyperium (idk if its gonna reproduce the crash)

**Desktop (please complete the following information):**  
 - OS: Windows 7  
 - Version Hyperium 1.2.2

**Additional context**  
  
fix the download for Hyperium-LOCAL.jar
actually using the og minecraft launcher now
**Logs**  
  
15:30:54.899
Preparing to launch minecraft client for Hyperium 1.8.9
15:30:58.420
Couldn't fetch SHA1 checksum for https://libraries.minecraft.net/optifine/OptiFine/1.8.9_HD_U_I7/OptiFine-1.8.9_HD_U_I7.jar
15:30:58.422
Have local file C:\Users\ANH TRUC\AppData\Roaming\.minecraft\libraries\optifine\OptiFine\1.8.9_HD_U_I7\OptiFine-1.8.9_HD_U_I7.jar but don't know what size or hash it should be. Have to assume it's good.
15:30:58.466
Couldn't fetch SHA1 checksum for https://libraries.minecraft.net/cc/hyperium/Hyperium/LOCAL/Hyperium-LOCAL.jar
15:30:58.466
Have local file C:\Users\ANH TRUC\AppData\Roaming\.minecraft\libraries\cc\hyperium\Hyperium\LOCAL\Hyperium-LOCAL.jar but don't know what size or hash it should be. Have to assume it's good.
15:30:58.469
Checking installations.
15:30:58.470
Minecraft client Hyperium 1.8.9 is ready to start.
15:30:58.470
Starting!
15:30:59.849
Using default game log configuration client-1.7.xml (outputs XML)
15:31:00.606
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
15:31:00.606
Process crashed with exit code 1

**Comment by Systemless03** [comment]
The JVM can't allocate enough ram. Try allocating less ram. Join our discord for further support. https://discord.gg/sk1er
