### ISSUE TITLE
Rear view continued to work after unbinding its key in the hyperium settings

### ISSUE THREAD

**Issue by abysstard** [HyperiumClient/Hyperium#747]
**Describe the bug**  
 So what the problem is, is that I have unbinded the rear view key because i have my R key to sprint. But even after unbinding it in settings it still continued to do rear view.

**To Reproduce**  
1.  Unbind the key
2.  Bind to a different key

**Expected behavior**  
  I expected rear view bind to not exist in my binds. Since I wanted to unbind it. Though, I have figured out that binding it to a different key that I don't use may work, but regardless, it is still a bug that needs to be fixed. Thank you.

**Screenshots**  
  

**Desktop (please complete the following information):**  
 - Windows 10
 - Optifine Version: Optifine_1.8.9_HD_U_L5,jar
- Hyperium Version 1.2.2 build 2776

**Additional context**
  

**Logs**

**Comment by asbyth** [comment]
Keybinds are incredibly buggy in 1.2.2 for whatever reason, randomly started. We have a manual "fix" to this issue while 1.3 is in development.
In the meantime, you can go to https://minecraft.gamepedia.com/Key_codes and find the key code for what you want to bind a certain function to, and head over to your `hyperium` folder's `keybinds.json` to enter it in manually. Depending on your OS, your Minecraft directory will be different.
