### ISSUE TITLE
Build Bug - deprecrated gradle software (on 7) - fails w/ * What went wrong: A problem occurred evaluating root project 'Hyperium'. > 'org.gradle.api.tasks.TaskOutputs org.gradle.api.internal.TaskOutputsInternal.dir(java.lang.Object)'

### ISSUE THREAD

**Issue by ItzSwirlz** [HyperiumClient/Hyperium#750]
OS: Ubuntu 20.04 LTS
DE: GNOME 3 Shell
Gradle Info:
------------------------------------------------------------
Gradle 6.3
------------------------------------------------------------

Build time:   2020-03-24 19:52:07 UTC
Revision:     bacd40b727b0130eeac8855ae3f9fd9a0b207c60

Kotlin:       1.3.70
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.7 (Ubuntu 11.0.7+10-post-Ubuntu-3ubuntu1)
OS:           Linux 5.4.0-29-generic amd64

Fails with:
A problem occurred evaluating root project 'Hyperium'. > 'org.gradle.api.tasks.TaskOutputs org.gradle.api.internal.TaskOutputsInternal.dir(java.lang.Object)'

Showing stacktrace/info doesn't show anything.

I used to build MC Mods so I'm a little familiar with gradle but I can't really do any hard debugging :page_facing_up:

**Comment by asbyth** [comment]
Just getting to this, if on master branch, you will need to use Gradle 4.10.3-all as ForgeGradle 2.1 does not support 5+.
If on mcgradle branch, you will need to use 5.6.2-all as ForgeGradle will still limit MCGradle to under 6+.
