### ISSUE TITLE
ChatTriggers is outdated, experiencing module issues as a result.

### ISSUE THREAD

**Issue by dtomvan** [HyperiumClient/Hyperium#751]
**Describe the bug**  

I have a problem with the chattriggers mod. If it opens a gui, then I get my cursor in-game but there is no gui showing up. When I hit esc I go back to the game and play normal. Also my commands that are included with. For example, the hypixel utilities just show up as command not found. I talked about this in the discord of the mod and they set hyperium has an old version of the mod, so maybe that is the reason why.

**To Reproduce**  
1.  Install a module with /CT import hypixelutilities
2.  Issue the command /hu from the module

**Expected behavior**  
  
The hypixel utilities module gui should show up.

**Screenshots**  
  
Cannot screen right now but if asked I will post some.

**Desktop (please complete the following information):**  
 - OS: Windows 10
 - Release: 1.2.3 using the universal installer.

**Additional context**
  

**Logs**

**Comment by asbyth** [comment]
Known, I plan on updating ChatTriggers some day however it's going to be a big task.

**Comment by 18gatenmaker** [comment]
Ok so what do i do should i use something else in the meantime?

**Comment by asbyth** [comment]
> 
> 
> Ok so what do i do should i use something else in the meantime? Like just plain forge?

Probably, a good replacement and similar experience would be our mod, [Patcher](https://sk1er.club/mods/patcher)
