### ISSUE TITLE
Perspective Mod

### ISSUE THREAD

**Issue by AkaHusky24** [HyperiumClient/Hyperium#758]
Perspective Mod

**Is your feature request related to a problem? If so, please describe.**   
  
I have problem with controlls.

**Describe the solution you'd like**
  
I'd like to add swap Y axis button because it's uncontrollable for me.

**Comment by asbyth** [comment]
can you explain what you mean in better detail?

**Comment by GamingRedCZ** [comment]
> can you explain what you mean in better detail?
I mean if you can make the controlls work like in (BADLION CLIENT), because it's so hard to controll it, If it is possible to swap mouse Y axis on the perspective mod.
