### ISSUE TITLE
Memory leaks possibly still lurking around.

### ISSUE THREAD

**Issue by sebaju** [HyperiumClient/Hyperium#760]
**Describe the bug**  
When I launch hyperium on mmc the game has frequent lag spikes and eventually freezes.

**To Reproduce**  
1.  Install to mmc home folder with optifine and arrow trails.
2.  Launch.
3.  Play on a server.

**Expected behavior**  
The game was to run smoothly.

  

**Desktop (please complete the following information):**  
 - Fedora 32
 - Release 1.3.2

**Additional context**
I tried with default setting and tampered settings and the bug happens in both situations.

**Comment by asbyth** [comment]
memory issues may be fixed in the mcgradle branch, as i suppose this is another memory leak. let me know once 1.3 is released, when that will be i dont know
