### ISSUE TITLE
Copyright Error

### ISSUE THREAD

**Issue by GarfieldKart** [HyperiumClient/Hyperium#81]
You know you cant copyright Hyperium right? almost nothing in this is made by you and it's just an extension of Minecraft

**Comment by Amplifiable** [comment]
are you dumb? everything in this repo is made by them so they can copyright it

**Comment by VRCube** [comment]
Are you retarded? Everything in this repo was made by us. Every lines of code we coded, it was hard work.

**Comment by Eros** [comment]
"Every lines of code we coded" https://imgur.com/a/pKWU8

**Comment by IsaiahPatton** [comment]
While Auto-tip is made by a different person, it is open-sourced under a GPL compatible license (Apache 2.0) allowing it to be included in GPL projects, According to the FSF.
