### ISSUE TITLE
Hyperium menu style weird size

### ISSUE THREAD

**Issue by brunohpaiva** [HyperiumClient/Hyperium#87]
![screenshot_7](https://user-images.githubusercontent.com/15240571/38150497-7fc1e31e-3435-11e8-80cd-aed7144847e2.png)

**Comment by boomboompower** [comment]
Screenshot?

**Comment by boomboompower** [comment]
Are you playing in full screen mode?

**Comment by brunohpaiva** [comment]
Oh, that's it, with windowed fullscreen off is now ok
Thanks
